// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: retrievedoc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentScorer_RetrieveDocument_FullMethodName = "/tfidf.DocumentScorer/RetrieveDocument"
)

// DocumentScorerClient is the client API for DocumentScorer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentScorerClient interface {
	RetrieveDocument(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Document, error)
}

type documentScorerClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentScorerClient(cc grpc.ClientConnInterface) DocumentScorerClient {
	return &documentScorerClient{cc}
}

func (c *documentScorerClient) RetrieveDocument(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Document)
	err := c.cc.Invoke(ctx, DocumentScorer_RetrieveDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentScorerServer is the server API for DocumentScorer service.
// All implementations must embed UnimplementedDocumentScorerServer
// for forward compatibility.
type DocumentScorerServer interface {
	RetrieveDocument(context.Context, *Query) (*Document, error)
	mustEmbedUnimplementedDocumentScorerServer()
}

// UnimplementedDocumentScorerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentScorerServer struct{}

func (UnimplementedDocumentScorerServer) RetrieveDocument(context.Context, *Query) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveDocument not implemented")
}
func (UnimplementedDocumentScorerServer) mustEmbedUnimplementedDocumentScorerServer() {}
func (UnimplementedDocumentScorerServer) testEmbeddedByValue()                        {}

// UnsafeDocumentScorerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentScorerServer will
// result in compilation errors.
type UnsafeDocumentScorerServer interface {
	mustEmbedUnimplementedDocumentScorerServer()
}

func RegisterDocumentScorerServer(s grpc.ServiceRegistrar, srv DocumentScorerServer) {
	// If the following call pancis, it indicates UnimplementedDocumentScorerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentScorer_ServiceDesc, srv)
}

func _DocumentScorer_RetrieveDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentScorerServer).RetrieveDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentScorer_RetrieveDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentScorerServer).RetrieveDocument(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentScorer_ServiceDesc is the grpc.ServiceDesc for DocumentScorer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentScorer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tfidf.DocumentScorer",
	HandlerType: (*DocumentScorerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveDocument",
			Handler:    _DocumentScorer_RetrieveDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "retrievedoc.proto",
}
