# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: retrievedoc.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'retrievedoc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11retrievedoc.proto\x12\x05tfidf\"\x15\n\x05Query\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x18\n\x08\x44ocument\x12\x0c\n\x04text\x18\x01 \x01(\t2C\n\x0e\x44ocumentScorer\x12\x31\n\x10RetrieveDocument\x12\x0c.tfidf.Query\x1a\x0f.tfidf.DocumentB\x1bZ\x19tfidf-service/proto/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retrievedoc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031tfidf-service/proto/proto'
  _globals['_QUERY']._serialized_start=28
  _globals['_QUERY']._serialized_end=49
  _globals['_DOCUMENT']._serialized_start=51
  _globals['_DOCUMENT']._serialized_end=75
  _globals['_DOCUMENTSCORER']._serialized_start=77
  _globals['_DOCUMENTSCORER']._serialized_end=144
# @@protoc_insertion_point(module_scope)
